import 'package:minimalist_converter/common/models/currency.dart';

final currencies = [
  Currency('USD', 'United States Dollar', '\$'),
  Currency('EUR', 'Euro', '€'),
  Currency('MXN', 'Mexican Peso', '\$'),
  Currency('AUD', 'Australian Dollar', 'A\$'),
  Currency('HKD', 'Hong Kong Dollar', 'HK\$'),
  Currency('RON', 'Romanian Leu', 'Lei'),
  Currency('HRK', 'Croatian Kuna', 'kn'),
  Currency('CHF', 'Swiss Franc', 'CHF'),
  Currency('IDR', 'Indonesian Rupiah', 'rp'),
  Currency('CAD', 'Canadian Dollar', '\$'),
  Currency('ZAR', 'South African Rand', 'R'),
  Currency('JPY', 'Japanese Yen', '¥'),
  Currency('BRL', 'Brazilian Real', 'R\$'),
  Currency('HUF', 'Hungarian Forint', 'ft'),
  Currency('CZK', 'Czech Koruna', 'Kč'),
  Currency('NOK', 'Norwegian Krone', 'kr'),
  Currency('INR', 'Indian Rupee', '₹'),
  Currency('PLN', 'Polish Zloty', 'zl'),
  Currency('ISK', 'Icelandic Krona', 'kr'),
  Currency('PHP', 'Philippines Peso', '₱'),
  Currency('SEK', 'Swedish Krona', 'kr'),
  Currency('ILS', 'Israeli Shekel', '₪'),
  Currency('GBP', 'British Pound', '£'),
  Currency('SGD', 'Singapore Dollar', 'S\$'),
  Currency('CNY', 'Chinese Yuan', '¥'),
  Currency('TRY', 'Turkish Lira', '₺'),
  Currency('MYR', 'Malaysian Ringgit', 'RM'),
  Currency('RUB', 'Russian Ruble', '₽'),
  Currency('NZD', 'New Zealand Dollar', 'NZ\$'),
  Currency('KRW', 'Korean Won', '₩'),
  Currency('THB', 'Thai Baht', '฿'),
  Currency('BGN', 'Bulgarian Lev', 'лв'),
  Currency('DKK', 'Danish Krone', 'kr')
];
